### ISSUE TITLE
an error occurred when running

### ISSUE THREAD

**Issue by marialui** [zanglab/bart2#6]
bart2 geneset -i genelist.txt -s hg38 --outdir bart2_output

Traceback (most recent call last):

  File "/home/maria/anaconda3/bin/bart2", line 4, in <module>

    __import__('pkg_resources').run_script('bart2==2.1', 'bart2')

  File "/home/maria/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File "/home/maria/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script

    exec(code, namespace, namespace)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/bart2-2.1-py3.9.egg/EGG-INFO/scripts/bart2", line 183, in <module>

    main()

  File "/home/maria/anaconda3/lib/python3.9/site-packages/bart2-2.1-py3.9.egg/EGG-INFO/scripts/bart2", line 179, in main

    bart(args)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/bart2-2.1-py3.9.egg/bart2/main.py", line 93, in bart

    counting, udhs_predict_df = EnhancerIdentifier.main(enhancer_args)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/bart2-2.1-py3.9.egg/bart2/EnhancerIdentifier.py", line 52, in main

    chrom = RPRegress.read_hdf5(udhs_h5file, "chrom")

  File "/home/maria/anaconda3/lib/python3.9/site-packages/bart2-2.1-py3.9.egg/bart2/RPRegress.py", line 78, in read_hdf5

    a = h5file.get_node("/", sample_name)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/tables/file.py", line 1642, in get_node

    node = self._get_node(nodepath)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/tables/file.py", line 1590, in _get_node

    node = self._node_manager.get_node(nodepath)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/tables/file.py", line 432, in get_node

    node = self.node_factory(key)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/tables/group.py", line 1178, in _g_load_child

    node_type = self._g_check_has_child(childname)

  File "/home/maria/anaconda3/lib/python3.9/site-packages/tables/group.py", line 393, in _g_check_has_child

    raise NoSuchNodeError(

tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/chrom``

Closing remaining open files:/home/maria/Desktop/microarray-analysis/relapsing-remitting-10-01-2024/MAGE-attempt/OUTPUT/MEGA-results-on-blood/BART/bart_py2/hg38_library/bart2_hg38_UDHS_H3K27ac.h5...done

**Comment by marvinquiet** [comment]
Dear @marialui,

Sorry for the late reply. May I know if you are still encountering this problem?

Sincerely,
Wenjing
